[mcp_servers.chrome-devtools]
args = [
    "chrome-devtools-mcp@latest",
    "--autoConnect",
]
command = "npx"

[mcp_servers.gitnexus]
args = [
    "-y",
    "gitnexus",
    "mcp",
]
command = "npx"
