[package]
name = "macaca-tools"
version.workspace = true
edition.workspace = true

[dependencies]
macaca-proto = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid.workspace = true
futures = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
tempfile = "3"
