// SPDX-License-Identifier: Apache-2.0
//
// Derived from AgentScope Java 2.0 concepts and APIs.
// Copyright 2024-2026 the original AgentScope author or authors.
// Licensed under the Apache License, Version 2.0.

//! Additional Harness parity contracts.
//!
//! The existing Harness modules provide service ports. This module adds the
//! complete specification DTOs and state-machine records needed to audit
//! AgentScope 2.0 parity without moving concrete filesystem, sandbox, skill,
//! memory, or subagent implementations into the framework.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::event_contract::AgentEvent;

/// Two-layer workspace read strategy.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum WorkspaceReadLayer {
    FilesystemFirst,
    AuthorizedLocalFallback,
}

/// Workspace read contract used before any host-local fallback is considered.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct WorkspaceReadContract {
    pub layer: WorkspaceReadLayer,
    pub capability_ref: String,
    pub path_policy_ref: String,
    pub sandbox_ref: Option<String>,
}

/// Provider-neutral filesystem shape.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum HarnessFilesystemSpec {
    Local {
        root_ref: String,
    },
    Remote {
        endpoint_ref: String,
    },
    Sandbox {
        sandbox_ref: String,
    },
    Composite {
        members: Vec<HarnessFilesystemSpec>,
    },
    Overlay {
        lower: Box<HarnessFilesystemSpec>,
        upper: Box<HarnessFilesystemSpec>,
    },
    Baked {
        image_ref: String,
    },
}

/// Backend-neutral sandbox provider shape.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "sandbox_kind", rename_all = "snake_case")]
pub enum HarnessSandboxBackendSpec {
    Docker { profile_ref: String },
    E2b { profile_ref: String },
    Kubernetes { profile_ref: String },
    Daytona { profile_ref: String },
    AgentRun { profile_ref: String },
    Plugin { provider_ref: String },
    Remote { endpoint_ref: String },
    Mock { fixture_ref: String },
    Unavailable { reason: String },
}

/// Explicit sandbox lifecycle state for health, resume, and audit.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum HarnessSandboxLifecycleState {
    Requested,
    Acquired,
    Released,
    Unavailable,
    Denied,
    Failed,
}

/// Session tree memento used by Harness restore logic.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HarnessSessionNode {
    pub session_id: String,
    pub parent_session_id: Option<String>,
    pub child_session_ids: Vec<String>,
    pub freshness_ref: Option<String>,
    pub checkpoint_ref: Option<String>,
    pub updated_at: DateTime<Utc>,
}

impl HarnessSessionNode {
    pub fn root(session_id: impl Into<String>) -> Self {
        Self {
            session_id: session_id.into(),
            parent_session_id: None,
            child_session_ids: Vec::new(),
            freshness_ref: None,
            checkpoint_ref: None,
            updated_at: Utc::now(),
        }
    }
}

/// Memory maintenance command kind.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum HarnessMemoryMaintenanceKind {
    Consolidate,
    Flush,
    SearchSessionMemory,
}

/// Schedule/result DTO for service-backed memory maintenance.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct HarnessMemoryMaintenanceRecord {
    pub maintenance_id: String,
    pub kind: HarnessMemoryMaintenanceKind,
    pub schedule_ref: Option<String>,
    pub evidence_ref: Option<String>,
    pub completed: bool,
    pub reason: Option<String>,
}

/// Skill resource visibility state used before prompt projection.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum HarnessSkillVisibility {
    Hidden,
    PromptVisible,
    ToolVisible,
}

/// Skill resource DTO. Raw package bytes and decrypted materials are omitted.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct HarnessSkillResourceSpec {
    pub resource_id: String,
    pub lazy: bool,
    pub visibility: HarnessSkillVisibility,
    pub conflict_group: Option<String>,
    pub promotion_ref: Option<String>,
    pub audit_ref: Option<String>,
}

/// Dynamic subagent spec generated by a service or provider-neutral builder.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct HarnessSubagentDynamicSpec {
    pub subagent_id: String,
    pub spec_generator_ref: String,
    pub workspace_mode: String,
    pub remote_stub_ref: Option<String>,
    pub forward_stream: bool,
}

/// Nested child event projection for subagent stream forwarding.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HarnessChildEventProjection {
    pub parent_event_source_id: String,
    pub child_event_source_id: String,
    pub event: AgentEvent,
}

/// Plan tool kind. These are local framework plan tools, not Macaca TaskBoard
/// mutation commands.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum HarnessPlanToolKind {
    CreatePlan,
    UpdatePlan,
    InspectPlan,
}

/// Plan-mode state transition requested by the framework.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "transition", rename_all = "snake_case")]
pub enum HarnessPlanModeTransition {
    Enter { reason: String },
    Exit { hitl_required: bool, reason: String },
    UseTool { kind: HarnessPlanToolKind },
}

#[cfg(test)]
#[path = "harness_contracts_tests.rs"]
mod harness_contracts_tests;
