[package]
name = "macaca-persist"
version.workspace = true
edition.workspace = true

[dependencies]
macaca-proto = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
redb = "2"
chrono = { workspace = true }
[dev-dependencies]
tempfile = "3"
tokio = { workspace = true }