//! Facade for provider-neutral domain-pack contracts.
//!
//! # Role in the architecture
//!
//! The SDK exposes only catalog metadata, capability expansion, and registry
//! helpers from `macaca-proto`. Concrete package crates are installed by an
//! approved host composition root and never proxied through SDK features.
//!
//! # Trace and audit
//!
//! Catalog composition logs `registered_pack_count` at the proto layer.  Provider registration
//! logs remain in each package crate's bootstrap factory with `domain_pack` / `service_count`
//! provider-neutral dimensions.

/// Canonical domain-pack contract types and expansion helpers (proto-owned).
pub use macaca_proto::{
    calendar_stable_hash, communication_calendar_descriptor_hashes,
    communication_calendar_pack_definition, communication_email_descriptor_hashes,
    communication_email_pack_definition, communication_inbox_descriptor_hashes,
    communication_inbox_pack_definition, communication_messaging_descriptor_hashes,
    communication_messaging_pack_definition, communication_notification_descriptor_hashes,
    communication_notification_pack_definition, compose_installed_domain_pack_catalog,
    config_stable_hash, developer_pack_definition, email_stable_hash, empty_domain_pack_catalog,
    expand_service_capabilities, filesystem_stable_hash, foundation_config_descriptor_hashes,
    foundation_config_pack_definition, foundation_filesystem_descriptor_hashes,
    foundation_filesystem_pack_definition, foundation_key_value_state_descriptor_hashes,
    foundation_key_value_state_pack_definition, foundation_pack_definition,
    foundation_random_descriptor_hashes, foundation_random_pack_definition,
    foundation_secrets_reference_descriptor_hashes, foundation_secrets_reference_pack_definition,
    foundation_session_state_descriptor_hashes, foundation_session_state_pack_definition,
    foundation_time_descriptor_hashes, foundation_time_pack_definition, inbox_stable_hash,
    industrial_reference_domain_pack_definitions, key_value_state_stable_hash,
    knowledge_pack_definition, messaging_stable_hash, notification_stable_hash, random_stable_hash,
    reference_domain_pack_definitions, secrets_reference_stable_hash, session_state_stable_hash,
    snapshot_domain_pack_catalog, time_stable_hash, AppPackPolicyOverride,
    AppServiceContractConfig, AppServiceContractSpec, AppServicePolicyOverride, CalendarAttendee,
    CalendarAvailabilityQuery, CalendarCheckAvailabilityCommand, CalendarConference,
    CalendarConflict, CalendarCreateEventCommand, CalendarCursor, CalendarDeleteEventCommand,
    CalendarDescriptorHashes, CalendarError, CalendarEvent, CalendarExportIcalendarCommand,
    CalendarGetEventCommand, CalendarImportIcalendarCommand, CalendarInspectConflictsCommand,
    CalendarInstance, CalendarListCalendarsCommand, CalendarManageConferenceCommand,
    CalendarProposeTimesCommand, CalendarProviderCapability, CalendarProviderSnapshot,
    CalendarQueryEventsCommand, CalendarRecurrence, CalendarRegisterWatchCommand, CalendarReminder,
    CalendarRespondInviteCommand, CalendarResultEnvelope, CalendarResultStatus,
    CalendarSetReminderCommand, CalendarSource, CalendarSyncEventsCommand,
    CalendarUpdateEventCommand, CalendarWatch, ConfigDescribeSchemaCommand, ConfigDescriptorHashes,
    ConfigError, ConfigExplainProvenanceCommand, ConfigExportRedactedCommand, ConfigGetCommand,
    ConfigGetManyCommand, ConfigKeyReference, ConfigLayerReference, ConfigListKeysCommand,
    ConfigProvenance, ConfigProviderCapability, ConfigProviderSnapshot, ConfigRedactionSummary,
    ConfigReloadCommand, ConfigResolveEffectiveCommand, ConfigResultEnvelope, ConfigResultStatus,
    ConfigSchemaReference, ConfigSelector, ConfigSnapshotCommand, ConfigSourceReference,
    ConfigTypedValueRef, ConfigValidateCommand, ConfigValidationReport, ConfigValueKind,
    ConfigWatchCommand, ConfigWatchEvent, DomainPackAvailability, DomainPackCallableSpec,
    DomainPackCatalog, DomainPackCatalogSnapshot, DomainPackCompatibility,
    DomainPackDataGovernance, DomainPackDefinition, DomainPackDefinitionSpec,
    DomainPackDiagnostics, DomainPackEffectiveCapabilityProjection, DomainPackHierarchySpec,
    DomainPackIdentitySpec, DomainPackMetadata, DomainPackPolicyTemplate,
    DomainPackProviderCapabilityReport, DomainPackProviderCapabilityState,
    DomainPackProviderDescriptor, DomainPackProviderSnapshot, DomainPackSdkMetadata,
    DomainPackStability, DomainPackUnavailableDiagnostic, EffectiveServiceCapabilities,
    EmailApplyLabelsCommand, EmailAttachmentRef, EmailBodyKind, EmailBodyPart,
    EmailCancelScheduledSendCommand, EmailComposeCommand, EmailConsentStatus, EmailDeliveryState,
    EmailDeliveryStatusCommand, EmailDescriptorHashes, EmailDraftRef, EmailError,
    EmailFetchAttachmentCommand, EmailFetchMessageCommand, EmailIngestEventCommand,
    EmailListThreadsCommand, EmailMarkReadCommand, EmailMessageRef, EmailProviderCapability,
    EmailProviderEventRef, EmailProviderSnapshot, EmailRateLimitStatus, EmailRecipient,
    EmailRecipientKind, EmailResultEnvelope, EmailResultStatus, EmailSaveDraftCommand,
    EmailScheduleSendCommand, EmailSendCommand, EmailSenderRef, EmailSyncCursor,
    EmailSyncMailboxCommand, EmailUpdateDraftCommand, EmailValidateRecipientsCommand,
    FilesystemAccessMode, FilesystemAppendFileCommand, FilesystemCloseHandleCommand,
    FilesystemConflictMode, FilesystemContentRef, FilesystemCopyPathCommand,
    FilesystemCreateDirectoryCommand, FilesystemCreateTempCommand, FilesystemDeletePathCommand,
    FilesystemDescriptorHashes, FilesystemError, FilesystemHandleRef,
    FilesystemListDirectoryCommand, FilesystemMetadata, FilesystemMovePathCommand,
    FilesystemOpenHandleCommand, FilesystemPathRef, FilesystemProviderCapability,
    FilesystemProviderSnapshot, FilesystemReadFileCommand, FilesystemRestoreSnapshotCommand,
    FilesystemResultEnvelope, FilesystemResultStatus, FilesystemRootRef, FilesystemSnapshotRef,
    FilesystemSnapshotTreeCommand, FilesystemStatPathCommand, FilesystemWatchEvent,
    FilesystemWatchPathCommand, FilesystemWriteFileCommand, InMemoryDomainPackCatalog,
    InboxArchiveItemCommand, InboxAttachmentHandle, InboxClaim, InboxClaimItemCommand, InboxCursor,
    InboxDescriptorHashes, InboxError, InboxEvent, InboxFetchAttachmentCommand,
    InboxFetchBodyCommand, InboxGetItemCommand, InboxIngestEventCommand, InboxItem, InboxLabel,
    InboxLabelItemCommand, InboxListItemsCommand, InboxListThreadsCommand, InboxMarkReadCommand,
    InboxMoveItemCommand, InboxProviderCapability, InboxProviderSnapshot,
    InboxRegisterSourceCommand, InboxReleaseItemCommand, InboxResultEnvelope, InboxResultStatus,
    InboxResumeSyncCommand, InboxRevokeSourceCommand, InboxSearchItemsCommand, InboxSource,
    InboxSummarizeItemCommand, InboxSyncCheckpoint, InboxSyncSourcesCommand, InboxThread,
    InboxUpdateSourceCommand, KeyValueBatchDeleteCommand, KeyValueBatchGetCommand,
    KeyValueBatchPutCommand, KeyValueCompactNamespaceCommand, KeyValueCompareAndSetCommand,
    KeyValueConflictMode, KeyValueConsistencyLevel, KeyValueDeleteCommand, KeyValueExistsCommand,
    KeyValueGetCommand, KeyValueGetTtlCommand, KeyValueIncrementCommand, KeyValueKeyRef,
    KeyValueListKeysCommand, KeyValueMigrateNamespaceCommand, KeyValueNamespaceRef,
    KeyValuePutCommand, KeyValueRestoreNamespaceCommand, KeyValueRevision, KeyValueSetTtlCommand,
    KeyValueSnapshotNamespaceCommand, KeyValueSnapshotRef, KeyValueStateDescriptorHashes,
    KeyValueStateError, KeyValueStateProviderCapability, KeyValueStateProviderSnapshot,
    KeyValueStateResultEnvelope, KeyValueStateResultStatus, KeyValueTtlPolicy,
    KeyValueTypedValueRef, KeyValueWatchEvent, KeyValueWatchNamespaceCommand,
    MessagingAttachHandleCommand, MessagingAttachmentRef, MessagingContent,
    MessagingConversationKind, MessagingConversationRef, MessagingCreateConversationCommand,
    MessagingCursor, MessagingDeleteMessageCommand, MessagingDeliveryState,
    MessagingDeliveryStatusCommand, MessagingDescriptorHashes, MessagingEditMessageCommand,
    MessagingError, MessagingFetchMessageCommand, MessagingFindConversationCommand,
    MessagingIngestEventCommand, MessagingInspectParticipantsCommand, MessagingListMessagesCommand,
    MessagingMarkReadCommand, MessagingMessageRef, MessagingParticipantRef,
    MessagingProviderCapability, MessagingProviderEventRef, MessagingProviderSnapshot,
    MessagingRateLimitStatus, MessagingReaction, MessagingReactionCommand,
    MessagingReplyMessageCommand, MessagingResultEnvelope, MessagingResultStatus,
    MessagingSendMessageCommand, MessagingSendTypingCommand, MessagingSenderRef,
    NotificationAcknowledgeCommand, NotificationActionDefinition, NotificationActionEvent,
    NotificationCancelCommand, NotificationDeliveryChannel, NotificationDeliveryHandle,
    NotificationDeliveryStatus, NotificationDescriptorHashes, NotificationDismissCommand,
    NotificationError, NotificationInspectDeliveryCommand, NotificationListNotificationsCommand,
    NotificationMessage, NotificationProviderCapability, NotificationProviderSnapshot,
    NotificationPublishCommand, NotificationRegisterActionCommand,
    NotificationRegisterSubscriptionCommand, NotificationResultEnvelope, NotificationResultStatus,
    NotificationRevokeSubscriptionCommand, NotificationSchedule, NotificationScheduleCommand,
    NotificationSubscriptionHandle, NotificationTarget, NotificationUnregisterActionCommand,
    NotificationUpdateCommand, RandomAlphabetClass, RandomBytesCommand, RandomDescriptorHashes,
    RandomEntropyHealth, RandomEntropyHealthCommand, RandomError, RandomFillCommand,
    RandomIntegerCommand, RandomNonceCommand, RandomOutputEncoding,
    RandomProviderCapabilitiesCommand, RandomProviderCapability, RandomProviderSnapshot,
    RandomPurpose, RandomReplayPolicy, RandomResultEnvelope, RandomResultStatus,
    RandomSeedReference, RandomStreamReference, RandomStrengthClass, RandomTestStreamBytesCommand,
    RandomTestStreamCreateCommand, RandomTokenCommand, RandomUuidV4Command, SecretAccessPolicy,
    SecretAuditRecord, SecretExternalLocator, SecretLeaseReference, SecretPurposeBinding,
    SecretReference, SecretResolutionHandle, SecretVersionState, SecretVersionStatus,
    SecretsAuditAccessCommand, SecretsBindPurposeCommand, SecretsCreateLeaseCommand,
    SecretsCreateReferenceCommand, SecretsImportReferenceCommand, SecretsInspectReferenceCommand,
    SecretsListReferencesCommand, SecretsReferenceDescriptorHashes, SecretsReferenceError,
    SecretsReferenceProviderCapability, SecretsReferenceProviderSnapshot,
    SecretsReferenceResultEnvelope, SecretsReferenceResultStatus, SecretsRenewLeaseCommand,
    SecretsResolveForProviderCommand, SecretsRevokeLeaseCommand, SecretsRotateReferenceCommand,
    SecretsVersionStatusCommand, SessionStateCheckpointRef, SessionStateClearSessionCommand,
    SessionStateCompactHistoryCommand, SessionStateCompareCheckpointCommand,
    SessionStateCreateCheckpointCommand, SessionStateDeleteCommand, SessionStateDescriptorHashes,
    SessionStateError, SessionStateExportRedactedCommand, SessionStateGetCommand,
    SessionStateInspectRecoveryCommand, SessionStateKeyRef, SessionStateListCheckpointsCommand,
    SessionStateListKeysCommand, SessionStateMergePatchCommand, SessionStateProviderCapability,
    SessionStateProviderSnapshot, SessionStatePutCommand, SessionStateRecoveryMetadata,
    SessionStateRedactionSummary, SessionStateRestoreCheckpointCommand, SessionStateRestorePlan,
    SessionStateResultEnvelope, SessionStateResultStatus, SessionStateRetentionPolicy,
    SessionStateRevision, SessionStateSessionRef, SessionStateValueRef, SharedDomainPackCatalog,
    TimeAddDurationCommand, TimeCalendarConvertCommand, TimeCalendarReference,
    TimeCancelTimerCommand, TimeClockHealth, TimeClockHealthCommand, TimeClockSource,
    TimeConvertTimezoneCommand, TimeCreateTimerCommand, TimeDeadlineSpec, TimeDescriptorHashes,
    TimeDuration, TimeDurationBetweenCommand, TimeError, TimeEvaluateDeadlineCommand,
    TimeExactnessHint, TimeFormatCommand, TimeFormatSpec, TimeInspectTimerCommand, TimeInstant,
    TimeLocaleReference, TimeMonotonicInstant, TimeMonotonicNowCommand, TimeNowCommand,
    TimeParseCommand, TimeProviderCapability, TimeProviderSnapshot, TimeResolveTimezoneCommand,
    TimeResultEnvelope, TimeResultStatus, TimeTimerReference, TimeZoneReference,
    COMMUNICATION_CALENDAR_COMMANDS, COMMUNICATION_CALENDAR_PACK_ID,
    COMMUNICATION_CALENDAR_SERVICE_ID, COMMUNICATION_EMAIL_COMMANDS, COMMUNICATION_EMAIL_PACK_ID,
    COMMUNICATION_EMAIL_SERVICE_ID, COMMUNICATION_INBOX_COMMANDS, COMMUNICATION_INBOX_PACK_ID,
    COMMUNICATION_INBOX_SERVICE_ID, COMMUNICATION_MESSAGING_COMMANDS,
    COMMUNICATION_MESSAGING_PACK_ID, COMMUNICATION_MESSAGING_SERVICE_ID,
    COMMUNICATION_NOTIFICATION_COMMANDS, COMMUNICATION_NOTIFICATION_PACK_ID,
    COMMUNICATION_NOTIFICATION_SERVICE_ID, FOUNDATION_CONFIG_COMMANDS, FOUNDATION_CONFIG_PACK_ID,
    FOUNDATION_CONFIG_SERVICE_ID, FOUNDATION_FILESYSTEM_COMMANDS, FOUNDATION_FILESYSTEM_PACK_ID,
    FOUNDATION_FILESYSTEM_SERVICE_ID, FOUNDATION_KEY_VALUE_STATE_COMMANDS,
    FOUNDATION_KEY_VALUE_STATE_PACK_ID, FOUNDATION_KEY_VALUE_STATE_SERVICE_ID,
    FOUNDATION_RANDOM_COMMANDS, FOUNDATION_RANDOM_PACK_ID, FOUNDATION_RANDOM_SERVICE_ID,
    FOUNDATION_SECRETS_REFERENCE_COMMANDS, FOUNDATION_SECRETS_REFERENCE_PACK_ID,
    FOUNDATION_SECRETS_REFERENCE_SERVICE_ID, FOUNDATION_SESSION_STATE_COMMANDS,
    FOUNDATION_SESSION_STATE_PACK_ID, FOUNDATION_SESSION_STATE_SERVICE_ID,
    FOUNDATION_TIME_COMMANDS, FOUNDATION_TIME_PACK_ID, FOUNDATION_TIME_SERVICE_ID,
};

/// Knowledge pack contracts re-exported as SDK data DTOs only.
///
/// This block deliberately forwards proto-owned descriptors, commands, results, and
/// hash helpers without importing any search engines, vector stores, document parsers,
/// citation resolvers, graph databases, model clients, prompt templates, or provider
/// composition roots into the SDK.
pub use macaca_proto::{
    citations_stable_hash, document_parsing_stable_hash, graph_stable_hash,
    knowledge_citations_descriptor_hashes, knowledge_citations_pack_definition,
    knowledge_document_parsing_descriptor_hashes, knowledge_document_parsing_pack_definition,
    knowledge_graph_descriptor_hashes, knowledge_graph_pack_definition,
    knowledge_retrieval_descriptor_hashes, knowledge_retrieval_pack_definition,
    knowledge_search_descriptor_hashes, knowledge_search_pack_definition,
    knowledge_summarization_descriptor_hashes, knowledge_summarization_pack_definition,
    retrieval_stable_hash, search_stable_hash, summarization_stable_hash, BibliographyStyle,
    CitationContributor, CitationDescriptorHashes, CitationEvidence, CitationExportResult,
    CitationIdentifier, CitationImportResult, CitationItem, CitationProviderCapability,
    CitationResultEnvelope, CitationResultStatus, CitationSelector, CitationSourceAnchor,
    CitationVerificationResult, CitationsCreateCitationCommand, CitationsExportCitationsCommand,
    CitationsFormatBibliographyCommand, CitationsFormatCitationCommand,
    CitationsImportCitationsCommand, CitationsInspectProviderCommand,
    CitationsInspectSourceAnchorCommand, CitationsLinkSourceSpanCommand,
    CitationsListCitationsCommand, CitationsResolveIdentifierCommand,
    CitationsUpdateCitationCommand, CitationsVerifyCitationCommand, CompressionMap, DocumentChunk,
    DocumentConfidence, DocumentElement, DocumentEmbeddedResource, DocumentEntity,
    DocumentFormField, DocumentGeometry, DocumentMetadata, DocumentOcrToken, DocumentPage,
    DocumentParseResult, DocumentParserCapability, DocumentParsingCancelParseJobCommand,
    DocumentParsingChunkDocumentCommand, DocumentParsingConvertToCanonicalCommand,
    DocumentParsingDescriptorHashes, DocumentParsingDetectFormatCommand,
    DocumentParsingExtractFormsCommand, DocumentParsingExtractLayoutCommand,
    DocumentParsingExtractMetadataCommand, DocumentParsingExtractTablesCommand,
    DocumentParsingExtractTextCommand, DocumentParsingGetParseJobCommand,
    DocumentParsingInspectParserCommand, DocumentParsingParseDocumentCommand,
    DocumentParsingResultEnvelope, DocumentParsingResultStatus,
    DocumentParsingStartParseJobCommand, DocumentParsingValidateDocumentCommand, DocumentSource,
    DocumentTable, DocumentTableCell, DocumentTextSpan, FormattedCitation,
    GraphDeleteGraphItemsCommand, GraphDeleteTriplesCommand, GraphDescriptorHashes, GraphEdge,
    GraphExportPlan, GraphExportSubgraphCommand, GraphFindPathCommand, GraphImportPlan,
    GraphImportSubgraphCommand, GraphInspectProvenanceCommand, GraphInspectProviderCommand,
    GraphInspectStoreCommand, GraphMergeEntitiesCommand, GraphNode, GraphPath, GraphProperty,
    GraphProvenance, GraphProviderCapability, GraphQuery, GraphQueryCommand, GraphQueryResult,
    GraphRegisterStoreCommand, GraphResultEnvelope, GraphResultStatus, GraphSchema, GraphStore,
    GraphTraversal, GraphTraverseCommand, GraphUpsertEdgeCommand, GraphUpsertNodeCommand,
    GraphUpsertSchemaCommand, GraphUpsertTripleCommand, GraphValidateQueryCommand,
    GraphValidateSchemaCommand, KnowledgeCommandEnvelope, KnowledgeError, KnowledgePage, ParseJob,
    ParserProfile, RdfStatement, RdfTerm, RetrievalBulkRetrieveCommand, RetrievalCandidate,
    RetrievalChunk, RetrievalCollection, RetrievalCursor, RetrievalDeleteRecordsCommand,
    RetrievalDescriptorHashes, RetrievalEvidenceBundle, RetrievalExpandContextCommand,
    RetrievalFreshness, RetrievalFusionStrategy, RetrievalInspectCollectionCommand,
    RetrievalInspectRecordCommand, RetrievalMetadataFilter, RetrievalNamespace,
    RetrievalPackageEvidenceCommand, RetrievalProviderCapability, RetrievalQuery,
    RetrievalQueryDiagnosticsCommand, RetrievalRangeRetrieveCommand, RetrievalRecord,
    RetrievalRefreshCollectionCommand, RetrievalRegisterCollectionCommand,
    RetrievalRerankContextCommand, RetrievalResultEnvelope, RetrievalResultStatus,
    RetrievalRetrieveByIdCommand, RetrievalRetrieveCommand, RetrievalUpsertRecordsCommand,
    RetrievalVectorSpace, SearchAnalyzerProfile, SearchAutocompleteCommand, SearchCorpus,
    SearchCursor, SearchDescriptorHashes, SearchExplainRankingCommand, SearchFacetRequest,
    SearchFacetsCommand, SearchField, SearchFilter, SearchHit, SearchIndexSchema,
    SearchIndexStatsCommand, SearchInspectIndexCommand, SearchProviderCapability, SearchQuery,
    SearchQueryDiagnosticsCommand, SearchRankingExplanation, SearchRankingProfile,
    SearchRefreshIndexCommand, SearchRegisterCorpusCommand, SearchResultEnvelope,
    SearchResultStatus, SearchSearchCommand, SearchSort, SearchSuggestCommand, SearchSynonymSet,
    SummarizationCompareSummariesCommand, SummarizationCompressContextCommand,
    SummarizationDescriptorHashes, SummarizationEvaluateSummaryCommand,
    SummarizationInspectProviderCommand, SummarizationInspectSummaryEvidenceCommand,
    SummarizationPlanCommand, SummarizationRefineSummaryCommand, SummarizationResultEnvelope,
    SummarizationResultStatus, SummarizationSummarizeCommand,
    SummarizationSummarizeConversationCommand, SummarizationSummarizeManyCommand,
    SummarizationSummarizeWithCitationsCommand, SummarizationValidateRequestCommand, SummaryClaim,
    SummaryComparisonReport, SummaryEvidenceLink, SummaryOutput, SummaryPlan,
    SummaryProviderCapability, SummaryQualityReport, SummaryRequest, SummarySource,
    KNOWLEDGE_CITATIONS_COMMANDS, KNOWLEDGE_CITATIONS_PACK_ID, KNOWLEDGE_CITATIONS_SERVICE_ID,
    KNOWLEDGE_DOCUMENT_PARSING_COMMANDS, KNOWLEDGE_DOCUMENT_PARSING_PACK_ID,
    KNOWLEDGE_DOCUMENT_PARSING_SERVICE_ID, KNOWLEDGE_GRAPH_COMMANDS, KNOWLEDGE_GRAPH_PACK_ID,
    KNOWLEDGE_GRAPH_SERVICE_ID, KNOWLEDGE_RETRIEVAL_COMMANDS, KNOWLEDGE_RETRIEVAL_PACK_ID,
    KNOWLEDGE_RETRIEVAL_SERVICE_ID, KNOWLEDGE_SEARCH_COMMANDS, KNOWLEDGE_SEARCH_PACK_ID,
    KNOWLEDGE_SEARCH_SERVICE_ID, KNOWLEDGE_SUMMARIZATION_COMMANDS, KNOWLEDGE_SUMMARIZATION_PACK_ID,
    KNOWLEDGE_SUMMARIZATION_SERVICE_ID,
};
