[package]
name = "macaca-driver"
version.workspace = true
edition.workspace = true

[dependencies]
macaca-proto = { workspace = true }
macaca-tools = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
libloading = "0.7"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
[dev-dependencies]
tokio = { workspace = true }
