//! Provider-neutral Entitlement Service DTOs.
//!
//! Entitlement Service owns authorization decisions, entitlement state,
//! metering, and audit query shapes.  The DTOs reuse Phase 08 commerce value
//! objects so SDK clients, runtime-host providers, app guards, and skill guards
//! share one policy vocabulary without depending on concrete Store providers.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::{
    CapabilityId, CommerceMetadata, DeveloperId, EntitlementDecision, EntitlementId,
    EntitlementRecord, KernelServiceId, MeteringEvent, PackageId, TraceContext,
};

/// Stable Entitlement Service id used by descriptors and SDK clients.
pub const ENTITLEMENT_SERVICE_ID: &str = "service.entitlement";

/// Entitlement Service command names.
pub const ENTITLEMENT_QUERY_COMMAND: &str = "entitlement.query";
pub const ENTITLEMENT_UPSERT_COMMAND: &str = "entitlement.upsert";
pub const ENTITLEMENT_REVOKE_COMMAND: &str = "entitlement.revoke";
pub const ENTITLEMENT_AUTHORIZE_INSTALL_COMMAND: &str = "entitlement.authorize.install";
pub const ENTITLEMENT_AUTHORIZE_START_COMMAND: &str = "entitlement.authorize.start";
pub const ENTITLEMENT_AUTHORIZE_CALL_COMMAND: &str = "entitlement.authorize.call";
pub const ENTITLEMENT_AUDIT_QUERY_COMMAND: &str = "entitlement.audit.query";
pub const ENTITLEMENT_METERING_RECORD_COMMAND: &str = "entitlement.metering.record";
pub const ENTITLEMENT_SNAPSHOT_COMMAND: &str = "entitlement.snapshot";

/// Scope shared by entitlement commands.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct EntitlementServiceScope {
    pub entitlement_id: Option<EntitlementId>,
    pub package_id: Option<PackageId>,
    pub developer_id: Option<DeveloperId>,
    pub application_id: Option<String>,
    pub session_id: Option<String>,
    pub capability_id: Option<CapabilityId>,
}

impl EntitlementServiceScope {
    /// Build a package-scoped entitlement command.
    pub fn package(package_id: PackageId, developer_id: DeveloperId) -> Self {
        Self {
            entitlement_id: None,
            package_id: Some(package_id),
            developer_id: Some(developer_id),
            application_id: None,
            session_id: None,
            capability_id: None,
        }
    }
}

/// Query one entitlement record or the effective package entitlement.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EntitlementQueryCommand {
    pub trace: TraceContext,
    pub scope: EntitlementServiceScope,
}

/// Upsert one entitlement record through the service boundary.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EntitlementUpsertCommand {
    pub trace: TraceContext,
    pub record: EntitlementRecord,
}

/// Revoke one entitlement by writing a revoked record state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EntitlementRevokeCommand {
    pub trace: TraceContext,
    pub scope: EntitlementServiceScope,
    pub reason: String,
}

/// Authorize package install using commerce metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EntitlementAuthorizeInstallCommand {
    pub trace: TraceContext,
    pub scope: EntitlementServiceScope,
    pub commerce: CommerceMetadata,
}

/// Authorize package start using commerce metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EntitlementAuthorizeStartCommand {
    pub trace: TraceContext,
    pub scope: EntitlementServiceScope,
    pub commerce: CommerceMetadata,
}

/// Authorize one paid capability call and optionally emit metering.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EntitlementAuthorizeCallCommand {
    pub trace: TraceContext,
    pub scope: EntitlementServiceScope,
    pub commerce: CommerceMetadata,
    pub quantity: u64,
    pub unit: String,
}

/// Query decision audit records for a package.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EntitlementAuditQueryCommand {
    pub trace: TraceContext,
    pub scope: EntitlementServiceScope,
    pub limit: Option<usize>,
}

/// Record a metering event generated by an already authorized call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EntitlementMeteringRecordCommand {
    pub trace: TraceContext,
    pub event: MeteringEvent,
}

/// Query a sanitized Entitlement Service snapshot.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EntitlementSnapshotCommand {
    pub trace: TraceContext,
}

/// Sanitized decision view safe for shell display and audit pages.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EntitlementDecisionView {
    pub entitlement_id: Option<EntitlementId>,
    pub package_id: PackageId,
    pub developer_id: DeveloperId,
    pub operation: String,
    pub state: String,
    pub allowed: bool,
    pub reason: String,
    pub decided_at: DateTime<Utc>,
}

impl From<EntitlementDecision> for EntitlementDecisionView {
    fn from(value: EntitlementDecision) -> Self {
        Self {
            entitlement_id: value.entitlement_id,
            package_id: value.package_id,
            developer_id: value.developer_id,
            operation: value.operation,
            state: value.state.to_string(),
            allowed: value.allowed,
            reason: value.reason,
            decided_at: value.decided_at,
        }
    }
}

/// Paged audit result with sanitized decision records.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EntitlementAuditPage {
    pub package_id: Option<PackageId>,
    pub decisions: Vec<EntitlementDecisionView>,
    pub next_offset: Option<usize>,
}

/// Sanitized Entitlement Service snapshot.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EntitlementServiceSnapshot {
    pub service_id: KernelServiceId,
    pub health: String,
    pub entitlement_count: usize,
    pub audit_count: usize,
    pub metering_count: usize,
    pub diagnostics: Vec<String>,
}

impl EntitlementServiceSnapshot {
    /// Build a healthy snapshot from safe counters.
    pub fn healthy(entitlement_count: usize, audit_count: usize, metering_count: usize) -> Self {
        Self {
            service_id: KernelServiceId::new(ENTITLEMENT_SERVICE_ID),
            health: "healthy".into(),
            entitlement_count,
            audit_count,
            metering_count,
            diagnostics: Vec::new(),
        }
    }

    /// Build an unavailable snapshot with diagnostics.
    pub fn unavailable(reason: impl Into<String>) -> Self {
        Self {
            service_id: KernelServiceId::new(ENTITLEMENT_SERVICE_ID),
            health: "unavailable".into(),
            entitlement_count: 0,
            audit_count: 0,
            metering_count: 0,
            diagnostics: vec![reason.into()],
        }
    }
}

pub type EntitlementQueryResult = Option<EntitlementRecord>;
pub type EntitlementAuthorizeResult = EntitlementDecisionView;

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use super::*;
    use crate::EntitlementState;

    #[test]
    fn entitlement_decision_view_round_trips() {
        let decision = EntitlementDecision::allow(
            PackageId::new("pkg.test"),
            DeveloperId::new("developer.test"),
            "start",
            EntitlementState::valid(),
        );
        let view = EntitlementDecisionView::from(decision);
        let encoded = serde_json::to_string(&view).unwrap();
        let decoded: EntitlementDecisionView = serde_json::from_str(&encoded).unwrap();
        assert!(decoded.allowed);
        assert_eq!(decoded.operation, "start");
    }

    #[test]
    fn upsert_command_round_trips() {
        let now = Utc::now();
        let command = EntitlementUpsertCommand {
            trace: TraceContext::new("trace-entitlement-upsert"),
            record: EntitlementRecord {
                entitlement_id: EntitlementId::new("entitlement.test"),
                package_id: PackageId::new("pkg.test"),
                developer_id: DeveloperId::new("developer.test"),
                state: crate::EntitlementState::valid(),
                granted_at: now,
                updated_at: now,
                expires_at: None,
                metadata: BTreeMap::from([("source".into(), "test".into())]),
            },
        };
        let encoded = serde_json::to_string(&command).unwrap();
        let decoded: EntitlementUpsertCommand = serde_json::from_str(&encoded).unwrap();
        assert_eq!(decoded.record.entitlement_id.as_str(), "entitlement.test");
    }
}
