//! Migration-debt allowlist for OS-layer files exceeding the 500-line constitution.
//!
//! Each row records a known oversized production `src/**/*.rs` file. The executable
//! gate rejects any NEW violation while this baseline converges toward zero rows.
//! Sync removals with OpenSpec task §4.5.1 / §6.1.6 when splitting modules.

use super::gate::FileSizeAllowlistEntry;

/// Returns the baseline oversized-file snapshot (generated 2026-06-07, iteration 28).
pub fn entries() -> Vec<FileSizeAllowlistEntry> {
    vec![
        FileSizeAllowlistEntry::new("crates/application/macaca-app/src/manifest_v1/yaml_adapter.rs", 614, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/application/macaca-app/src/model.rs", 764, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/application/macaca-app/src/runtime.rs", 580, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/application/macaca-app/src/service_projection.rs", 847, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/application/macaca-app/src/workflow.rs", 625, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/facade/macaca-sdk/src/mcp_client.rs", 578, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/facade/macaca-sdk/src/scheduler_client.rs", 504, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/facade/macaca-sdk/src/skill_client.rs", 699, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/facade/macaca-sdk/src/system_facade.rs", 639, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/foundation/macaca-proto/src/agent_execution_service.rs", 759, "foundation-proto", "P5"),
        FileSizeAllowlistEntry::new("crates/foundation/macaca-proto/src/application_manifest.rs", 539, "foundation-proto", "P5"),
        FileSizeAllowlistEntry::new("crates/foundation/macaca-proto/src/application_service.rs", 684, "foundation-proto", "P5"),
        FileSizeAllowlistEntry::new("crates/foundation/macaca-proto/src/config.rs", 1573, "foundation-proto", "P5"),
        FileSizeAllowlistEntry::new("crates/foundation/macaca-proto/src/execution_control_service.rs", 545, "foundation-proto", "P5"),
        FileSizeAllowlistEntry::new("crates/foundation/macaca-proto/src/heartbeat_service.rs", 558, "foundation-proto", "P5"),
        FileSizeAllowlistEntry::new("crates/foundation/macaca-proto/src/scheduled_agent_task_service.rs", 643, "foundation-proto", "P5"),
        FileSizeAllowlistEntry::new("crates/foundation/macaca-proto/src/tool_service.rs", 545, "foundation-proto", "P5"),
        FileSizeAllowlistEntry::new("crates/foundation/macaca-proto/src/types.rs", 1514, "foundation-proto", "P5"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-framework/src/a2a.rs", 873, "P4-framework", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-framework/src/agent.rs", 675, "P4-framework", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-framework/src/formatter.rs", 1354, "P4-framework", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-framework/src/mcp.rs", 1750, "P4-framework", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-framework/src/memory.rs", 1303, "P4-framework", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-framework/src/message.rs", 631, "P4-framework", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-framework/src/model_impls.rs", 893, "P4-framework", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-framework/src/pipeline.rs", 720, "P4-framework", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-framework/src/plan.rs", 934, "P4-framework", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-framework/src/react_agent.rs", 1040, "P4-framework", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-framework/src/tool.rs", 1042, "P4-framework", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime/src/agentic_loop.rs", 1266, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/application_execution_hosted.rs", 648, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/application_execution_remote_agent.rs", 567, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/application_service_provider.rs", 1022, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/autonomy_dispatch.rs", 931, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/autonomy_service_provider.rs", 745, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/autonomy_supervisor/heartbeat_agent_dispatch.rs", 1022, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/autonomy_supervisor/heartbeat_lane/tests.rs", 571, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/entitlement.rs", 550, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/executor/app_executor.rs", 1401, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/executor/fork_manager.rs", 931, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/executor/queue.rs", 545, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/lib.rs", 583, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/mcp_runtime.rs", 2575, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/mcp_service_provider.rs", 1048, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/plugin_marketplace_service_commands.rs", 517, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/skill_service_provider.rs", 801, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/skill_service_provider_curation.rs", 502, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/skill_service_provider_proposal_materialization.rs", 565, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/skill_service_provider_state.rs", 588, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/skill_service_provider_tests.rs", 1811, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/tool_family_providers.rs", 707, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/tool_service_invocation.rs", 678, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/wasm_runtime_provider/component_model.rs", 818, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/wasm_runtime_provider/component_model_tests.rs", 652, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/wasm_runtime_provider/default_provider.rs", 532, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/wasm_runtime_provider/hardened_provider.rs", 574, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/wasm_runtime_provider/host_import_bridge.rs", 1154, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/runtime/macaca-runtime-host/src/wasm_runtime_provider/host_import_tests.rs", 708, "P4-runtime-host", "P4"),
        FileSizeAllowlistEntry::new("crates/services/macaca-context/src/engine.rs", 972, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/services/macaca-context/src/governance/pipeline.rs", 518, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/services/macaca-context/src/memory.rs", 582, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/services/macaca-heartbeat/src/local_provider.rs", 557, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/services/macaca-llm/src/resilient.rs", 619, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/services/macaca-memory/src/isolated.rs", 502, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/services/macaca-scheduled-agent-task/src/local_provider.rs", 1022, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/services/macaca-scheduler/src/local_provider.rs", 869, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/services/macaca-skill/src/agent_skill.rs", 676, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/services/macaca-skill/src/governance_store.rs", 595, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/services/macaca-skill/src/provisioner.rs", 515, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/services/macaca-skill/src/runtime.rs", 692, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/services/macaca-task/src/plan_loop.rs", 687, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/services/macaca-task/src/runtime.rs", 1144, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/services/macaca-task/src/scheduler.rs", 541, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/services/macaca-task/src/todo_board.rs", 1155, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/services/macaca-task/src/todo_store.rs", 558, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/services/macaca-tools/src/todo.rs", 1244, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/shells/macaca-cli/src/skill_operations.rs", 682, "OS-layer-debt", "P5"),
        FileSizeAllowlistEntry::new("crates/shells/macaca-web/src/agent_execution_backend/tests.rs", 656, "P3-web-thin-shell", "P3"),
        FileSizeAllowlistEntry::new("crates/shells/macaca-web/src/app_ui_routes.rs", 605, "P3-web-thin-shell", "P3"),
        FileSizeAllowlistEntry::new("crates/shells/macaca-web/src/context_memory_injection.rs", 592, "P3-web-thin-shell", "P3"),
        FileSizeAllowlistEntry::new("crates/shells/macaca-web/src/context_reporting_model.rs", 608, "P3-web-thin-shell", "P3"),
        FileSizeAllowlistEntry::new("crates/shells/macaca-web/src/framework_toolkit.rs", 1642, "P3-web-thin-shell", "P3"),
        FileSizeAllowlistEntry::new("crates/shells/macaca-web/src/session.rs", 1424, "P3-web-thin-shell", "P3"),
        FileSizeAllowlistEntry::new("crates/shells/macaca-web/src/skill_mcp.rs", 705, "P3-web-thin-shell", "P3"),
        FileSizeAllowlistEntry::new("crates/shells/macaca-web/src/skill_operations_routes.rs", 704, "P3-web-thin-shell", "P3"),
        FileSizeAllowlistEntry::new("crates/shells/macaca-web/src/skill_self_evolution_observer.rs", 810, "P3-web-thin-shell", "P3"),
        FileSizeAllowlistEntry::new("crates/tests/macaca-integration-tests/src/pipeline_dry_run.rs", 711, "OS-layer-debt", "P5"),
    ]
}
