//! Runtime-owned local WASM guest SDK and toolchain test harness.
//!
//! The harness applies Facade, Proxy, Builder, Adapter, and Test Double
//! patterns without becoming a real guest SDK crate.  It gives runtime tests and
//! developer tooling a deterministic way to build guest-style host commands,
//! validate WIT/ABI labels, generate package/artifact fixtures, and exercise
//! mock host import outcomes while sharing the same provider-neutral DTOs used
//! by the real runtime host import bridge.

use std::collections::{BTreeMap, BTreeSet};

use chrono::{DateTime, Utc};
use macaca_proto::{
    AbilityImplementationKind, AbilityPermissionDeclaration, AbilityServiceRequirement,
    ApplicationAbilityDescriptor, ApplicationExport, ApplicationHostCommand,
    ApplicationHostCommandResult, ApplicationHostCommandStatus,
    ApplicationHostRequirementDeclaration, ApplicationImport, ApplicationManifestV1,
    ApplicationPermissionDeclaration, ApplicationRuntimeProfile, CapabilityId, DeveloperId,
    KernelServiceId, PackageId, PackageRuntimeKind, TraceContext, WasmComponentArtifactDescriptor,
    WASM_HOST_IMPORT_CAPABILITY, WASM_HOST_IMPORT_OPERATION, WASM_HOST_IMPORT_SERVICE_ID,
};
use serde_json::{json, Value};
use tracing::{info, warn};

use super::guest_harness_support::{
    ability_kind, artifact_fixture, local_result, operation_for_kind, outcome_key,
    permission_for_kind, sanitize_json, sanitize_label, sanitize_text,
};

/// Fixed timestamp used by generated fixture traces.
///
/// The runtime harness intentionally produces deterministic metadata-only
/// artifacts so SDK/toolchain tests can compare complete fixture structures in
/// golden-style assertions.  Real runtime execution still receives live
/// `TraceContext` values from callers; only this local harness freezes the
/// timestamp to keep generated examples reproducible and audit-friendly.
const FIXTURE_TRACE_TIMESTAMP: DateTime<Utc> = DateTime::UNIX_EPOCH;

/// Stable example fixture categories generated by the runtime harness.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum WasmExampleFixtureKind {
    Headless,
    GenUiRender,
    MemoryContextImport,
    ServiceUnavailable,
}

impl WasmExampleFixtureKind {
    /// Return a deterministic fixture suffix used only by local test data.
    fn suffix(&self) -> &'static str {
        match self {
            Self::Headless => "headless",
            Self::GenUiRender => "genui_render",
            Self::MemoryContextImport => "memory_context",
            Self::ServiceUnavailable => "service_unavailable",
        }
    }
}

/// Mock host import outcome used by local harness tests.
#[derive(Debug, Clone, PartialEq)]
pub enum WasmMockHostOutcome {
    Success(Value),
    Denied(String),
    Unavailable(String),
    Unsupported(String),
}

/// Report returned after local harness dispatch.
#[derive(Debug, Clone, PartialEq)]
pub struct WasmGuestHarnessReport {
    pub command: ApplicationHostCommand,
    pub result: ApplicationHostCommandResult,
}

/// Metadata-only fixture bundle generated for guest SDK/toolchain tests.
#[derive(Debug, Clone, PartialEq)]
pub struct WasmGuestHarnessFixture {
    pub fixture_id: String,
    pub kind: WasmExampleFixtureKind,
    pub manifest: ApplicationManifestV1,
    pub artifact: WasmComponentArtifactDescriptor,
    pub commands: Vec<ApplicationHostCommand>,
    pub expected_reason_code: String,
}

/// Deterministic WIT and ABI consistency report.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WasmToolchainFixtureReport {
    pub wit_imports: Vec<String>,
    pub wit_exports: Vec<String>,
    pub abi_imports: Vec<String>,
    pub abi_exports: Vec<String>,
    pub missing_imports: Vec<String>,
    pub missing_exports: Vec<String>,
}

impl WasmToolchainFixtureReport {
    /// Return whether every ABI import/export is represented by the WIT labels.
    pub fn is_consistent(&self) -> bool {
        self.missing_imports.is_empty() && self.missing_exports.is_empty()
    }
}

/// Local runtime harness for guest-style WASM host import tests.
#[derive(Debug, Clone)]
pub struct WasmGuestRuntimeHarness {
    fixture_id: String,
    trace_prefix: String,
    outcomes: BTreeMap<String, WasmMockHostOutcome>,
}

impl WasmGuestRuntimeHarness {
    /// Create a harness with deterministic fixture and trace identifiers.
    pub fn new(fixture_id: impl Into<String>) -> Self {
        let fixture_id = sanitize_label(fixture_id.into());
        Self {
            trace_prefix: format!("{fixture_id}.trace"),
            fixture_id,
            outcomes: BTreeMap::new(),
        }
    }

    /// Register a mock outcome for one import/service/operation tuple.
    pub fn mock_outcome(
        mut self,
        import: ApplicationImport,
        service_id: impl AsRef<str>,
        operation: impl AsRef<str>,
        outcome: WasmMockHostOutcome,
    ) -> Self {
        self.outcomes.insert(
            outcome_key(&import, service_id.as_ref(), operation.as_ref()),
            outcome,
        );
        self
    }

    /// Build a guest-style service proxy command.
    ///
    /// The command is the same shape the real host import bridge consumes:
    /// `ServiceCall`, trace context, target service metadata, operation
    /// metadata, and capability metadata.  No provider or business service is
    /// hard-coded; callers provide all service identifiers.
    pub fn service_call(
        &self,
        service_id: impl AsRef<str>,
        operation: impl AsRef<str>,
        capability: impl AsRef<str>,
        payload: Value,
    ) -> ApplicationHostCommand {
        let service_id = sanitize_label(service_id.as_ref());
        let operation = sanitize_label(operation.as_ref());
        let capability = sanitize_label(capability.as_ref());
        let mut metadata = BTreeMap::new();
        metadata.insert(WASM_HOST_IMPORT_SERVICE_ID.into(), service_id);
        metadata.insert(WASM_HOST_IMPORT_OPERATION.into(), operation);
        metadata.insert(WASM_HOST_IMPORT_CAPABILITY.into(), capability);
        ApplicationHostCommand {
            import: ApplicationImport::ServiceCall,
            payload: sanitize_json(payload),
            trace: Some(self.trace("service")),
            metadata,
        }
    }

    /// Build a guest-style trace emit command.
    pub fn trace_emit(&self, event: Value) -> ApplicationHostCommand {
        ApplicationHostCommand {
            import: ApplicationImport::TraceEmit,
            payload: sanitize_json(event),
            trace: Some(self.trace("trace_emit")),
            metadata: BTreeMap::new(),
        }
    }

    /// Build a guest-style UI render command.
    pub fn render(&self, surface: impl AsRef<str>, input: Value) -> ApplicationHostCommand {
        ApplicationHostCommand {
            import: ApplicationImport::UiRender,
            payload: json!({
                "surface": sanitize_label(surface.as_ref()),
                "input": sanitize_json(input),
            }),
            trace: Some(self.trace("render")),
            metadata: BTreeMap::new(),
        }
    }

    /// Build a guest-style storage get command.
    pub fn storage_get(&self, key: impl AsRef<str>) -> ApplicationHostCommand {
        ApplicationHostCommand {
            import: ApplicationImport::StorageGet,
            payload: json!({ "key": sanitize_label(key.as_ref()) }),
            trace: Some(self.trace("storage_get")),
            metadata: BTreeMap::new(),
        }
    }

    /// Dispatch a command through the local mock host import test double.
    pub fn dispatch(&self, command: ApplicationHostCommand) -> WasmGuestHarnessReport {
        let trace = command.trace.clone();
        let Some(trace) = trace.filter(|trace| !trace.trace_id.trim().is_empty()) else {
            let result = local_result(
                ApplicationHostCommandStatus::Rejected {
                    reason: "missing trace context".into(),
                },
                Value::Null,
                None,
                "missing_trace",
            );
            warn!(
                fixture_id = %self.fixture_id,
                import = %command.import,
                reason_code = "missing_trace",
                "WASM guest local harness rejected untraceable command"
            );
            return WasmGuestHarnessReport { command, result };
        };
        let service_id = command
            .metadata
            .get(WASM_HOST_IMPORT_SERVICE_ID)
            .map(String::as_str)
            .unwrap_or("");
        let operation = command
            .metadata
            .get(WASM_HOST_IMPORT_OPERATION)
            .map(String::as_str)
            .unwrap_or("");
        let key = outcome_key(&command.import, service_id, operation);
        let outcome = self.outcomes.get(&key).cloned().unwrap_or_else(|| {
            WasmMockHostOutcome::Unsupported("mock import not registered".into())
        });
        let result = match outcome {
            WasmMockHostOutcome::Success(output) => local_result(
                ApplicationHostCommandStatus::Ok,
                sanitize_json(output),
                Some(trace.clone()),
                "mock_import_completed",
            ),
            WasmMockHostOutcome::Denied(reason) => local_result(
                ApplicationHostCommandStatus::DisabledByPolicy {
                    reason: sanitize_text(reason),
                },
                Value::Null,
                Some(trace.clone()),
                "mock_import_denied",
            ),
            WasmMockHostOutcome::Unavailable(reason) => local_result(
                ApplicationHostCommandStatus::Unavailable {
                    reason: sanitize_text(reason),
                },
                Value::Null,
                Some(trace.clone()),
                "mock_import_unavailable",
            ),
            WasmMockHostOutcome::Unsupported(reason) => local_result(
                ApplicationHostCommandStatus::Unsupported {
                    reason: sanitize_text(reason),
                },
                Value::Null,
                Some(trace.clone()),
                "mock_import_unsupported",
            ),
        };
        info!(
            fixture_id = %self.fixture_id,
            trace_id = %trace.trace_id,
            import = %command.import,
            reason_code = result.metadata.get("reason_code").map(String::as_str).unwrap_or("none"),
            "WASM guest local harness dispatched mock host import"
        );
        WasmGuestHarnessReport { command, result }
    }

    /// Generate deterministic WIT/ABI label consistency data.
    pub fn wit_label_report(&self) -> WasmToolchainFixtureReport {
        let wit_imports = ApplicationImport::v0()
            .into_iter()
            .map(|import| import.as_name().to_string())
            .collect::<Vec<_>>();
        let wit_exports = ApplicationExport::required_v0()
            .into_iter()
            .map(|export| export.as_name().to_string())
            .collect::<Vec<_>>();
        let abi_imports = wit_imports.clone();
        let abi_exports = wit_exports.clone();
        let wit_import_set = wit_imports.iter().cloned().collect::<BTreeSet<_>>();
        let wit_export_set = wit_exports.iter().cloned().collect::<BTreeSet<_>>();
        let missing_imports = abi_imports
            .iter()
            .filter(|label| !wit_import_set.contains(*label))
            .cloned()
            .collect();
        let missing_exports = abi_exports
            .iter()
            .filter(|label| !wit_export_set.contains(*label))
            .cloned()
            .collect();
        WasmToolchainFixtureReport {
            wit_imports,
            wit_exports,
            abi_imports,
            abi_exports,
            missing_imports,
            missing_exports,
        }
    }

    /// Generate a metadata-only example application fixture.
    pub fn example_fixture(&self, kind: WasmExampleFixtureKind) -> WasmGuestHarnessFixture {
        let suffix = kind.suffix();
        let fixture_id = format!("{}.{}", self.fixture_id, suffix);
        let ability_id = format!("{fixture_id}.ability");
        let service_id = KernelServiceId::new(format!("{fixture_id}.service"));
        let capability = CapabilityId::new(format!("{fixture_id}.capability"));
        let ability = ApplicationAbilityDescriptor::new(
            ability_id.clone(),
            ability_kind(&kind),
            AbilityImplementationKind::WasmComponent,
        )
        .permission(AbilityPermissionDeclaration::required(
            permission_for_kind(&kind),
            "WASM fixture requires this provider-neutral host import permission",
        ))
        .service(
            AbilityServiceRequirement::required(
                service_id.clone(),
                "WASM fixture service dependency is declared for local harness checks",
            )
            .capability(capability.clone()),
        );
        let manifest = ApplicationManifestV1::new(
            PackageId::new(fixture_id.clone()),
            DeveloperId::new(format!("{}.developer", self.fixture_id)),
            format!("WASM {suffix} Fixture"),
            "1.0.0",
            ApplicationRuntimeProfile::new(PackageRuntimeKind::WasmComponent, "0")
                .entry("component.wasm"),
            ApplicationHostRequirementDeclaration::new("0.1.0"),
        )
        .ability(ability)
        .permission(ApplicationPermissionDeclaration::required(
            permission_for_kind(&kind),
            "WASM fixture declares required host import permission",
        ));
        let artifact = artifact_fixture(&fixture_id, &ability_id, permission_for_kind(&kind));
        let command = self.service_call(
            service_id.as_str(),
            operation_for_kind(&kind),
            capability.as_str(),
            json!({ "fixture": suffix }),
        );
        let expected_reason_code = match kind {
            WasmExampleFixtureKind::ServiceUnavailable => "mock_import_unavailable",
            _ => "mock_import_completed",
        }
        .into();
        WasmGuestHarnessFixture {
            fixture_id,
            kind,
            manifest,
            artifact,
            commands: vec![command],
            expected_reason_code,
        }
    }

    fn trace(&self, operation: &str) -> TraceContext {
        let mut trace = TraceContext::new(format!(
            "{}.{}",
            self.trace_prefix,
            sanitize_label(operation)
        ));
        trace.emitted_at = FIXTURE_TRACE_TIMESTAMP;
        trace
    }
}
