//! Explicit Skill service contract surface for SDK composition roots.
//!
//! Runtime-host owns Skill provider installation and dispatch.  The SDK imports
//! these DTOs through this facade so it can remain a service client without a
//! direct production dependency on the Skill crate.

pub use macaca_skill::{
    skill_service_descriptor, FilteredSkill, SelfEvolutionEvaluationCheckpoint,
    SelfEvolutionEvaluationCheckpointKind, SelfEvolutionEvaluationLifecycle,
    SelfEvolutionEvaluationRecord, SelfEvolutionReportRefs, SelfEvolutionRunMetrics,
    SelfEvolutionScore, SelfEvolutionWhiteBoxEvidence, SkillAliasKind, SkillAliasResolutionPolicy,
    SkillAliasResolutionStatus, SkillAliasResolveCommand, SkillAliasResolveResult,
    SkillAliasSnapshotCommand, SkillAliasSnapshotResult, SkillAliasUpsertCommand,
    SkillAliasUpsertResult, SkillAuthorKind, SkillAutonomousMaterializationRunCommand,
    SkillAutonomousMaterializationRunResult, SkillAutonomousMaterializationSnapshotCommand,
    SkillAutonomousMaterializationSnapshotResult, SkillCleanupCommand, SkillCurationDryRunCommand,
    SkillCurationDryRunResult, SkillCurationLifecycleAction, SkillCurationLifecycleCommand,
    SkillCurationLifecycleResult, SkillCurationRollbackCommand, SkillCurationRollbackResult,
    SkillCurationRunCommand, SkillCurationRunResult, SkillCurationSnapshotCommand,
    SkillCurationSnapshotResult, SkillEvaluationCheckpointAppendCommand,
    SkillEvaluationCheckpointAppendResult, SkillEvaluationReportCommand,
    SkillEvaluationReportResult, SkillEvaluationScoreCommand, SkillEvaluationScoreResult,
    SkillEvolutionCandidateClassification, SkillEvolutionPromoteDraftCommand,
    SkillEvolutionPromoteDraftResult, SkillEvolutionProposalAction,
    SkillEvolutionProposePatchCommand, SkillEvolutionProposePatchResult,
    SkillEvolutionRejectDraftCommand, SkillEvolutionRejectDraftResult, SkillExecutableLoadCommand,
    SkillExecutableLoadResult, SkillExperienceCandidate, SkillExperienceCandidateDestination,
    SkillExperienceEvidenceGateStatus, SkillExperienceProposalCommand,
    SkillExperienceProposalResult, SkillExperienceProposalSnapshotCommand,
    SkillExperienceProposalSnapshotResult, SkillGovernanceProvenance, SkillGovernanceRecord,
    SkillGovernanceRecordUsageCommand, SkillGovernanceRecordUsageResult,
    SkillGovernanceSnapshotCommand, SkillGovernanceSnapshotResult, SkillInstallSpec,
    SkillLifecycleState, SkillMcpServerConfig, SkillOperatorCatalogListCommand,
    SkillOperatorCatalogListResult, SkillOperatorChangedCommand, SkillOperatorChangedResult,
    SkillOperatorConfigWriteCommand, SkillOperatorConfigWriteResult,
    SkillOperatorEnablementCommand, SkillOperatorEnablementResult,
    SkillOperatorMarkdownReadCommand, SkillOperatorMarkdownReadResult, SkillOperatorUnwatchCommand,
    SkillOperatorWatchCommand, SkillOperatorWatchResult, SkillPackageOwnershipClass, SkillPolicy,
    SkillProposalProcessingRunCommand, SkillProposalProcessingRunResult,
    SkillProposalProcessingSnapshotCommand, SkillProposalProcessingSnapshotResult,
    SkillSemanticReviewResult, SkillServicePolicyHints, SkillServiceScope, SkillServiceSnapshot,
    SkillServiceSnapshotCommand, SkillSnapshot, SkillSnapshotEntry, SkillSnapshotServiceCommand,
    SkillSnapshotServiceResult, SkillSourceScope, SkillStatusCommand, SkillStatusResult,
    SkillToolCatalogCommand, SkillToolCatalogResult, SkillToolInvokeCommand, SkillToolInvokeResult,
    SkillUsageEventKind, SkillUsageObservation, SkillUsageTelemetry, SKILL_ALIAS_RESOLVE_COMMAND,
    SKILL_ALIAS_SNAPSHOT_COMMAND, SKILL_ALIAS_UPSERT_COMMAND, SKILL_CLEANUP_COMMAND,
    SKILL_CURATION_ARCHIVE_COMMAND, SKILL_CURATION_DRY_RUN_COMMAND, SKILL_CURATION_PIN_COMMAND,
    SKILL_CURATION_QUARANTINE_COMMAND, SKILL_CURATION_REJECT_COMMAND,
    SKILL_CURATION_RELEASE_QUARANTINE_COMMAND, SKILL_CURATION_RESTORE_COMMAND,
    SKILL_CURATION_ROLLBACK_COMMAND, SKILL_CURATION_RUN_COMMAND, SKILL_CURATION_SNAPSHOT_COMMAND,
    SKILL_CURATION_UNPIN_COMMAND, SKILL_EVALUATION_CHECKPOINT_APPEND_COMMAND,
    SKILL_EVALUATION_REPORT_COMMAND, SKILL_EVALUATION_SCORE_COMMAND,
    SKILL_EVOLUTION_MATERIALIZATION_OPERATOR_RUN_COMMAND,
    SKILL_EVOLUTION_MATERIALIZATION_OPERATOR_SNAPSHOT_COMMAND,
    SKILL_EVOLUTION_PROCESSING_RUN_COMMAND, SKILL_EVOLUTION_PROCESSING_SNAPSHOT_COMMAND,
    SKILL_EVOLUTION_PROMOTE_DRAFT_COMMAND, SKILL_EVOLUTION_PROPOSE_FROM_TASK_COMMAND,
    SKILL_EVOLUTION_PROPOSE_PATCH_COMMAND, SKILL_EVOLUTION_REJECT_DRAFT_COMMAND,
    SKILL_EVOLUTION_SNAPSHOT_COMMAND, SKILL_EXECUTABLE_LOAD_COMMAND,
    SKILL_GOVERNANCE_RECORD_USAGE_COMMAND, SKILL_GOVERNANCE_SNAPSHOT_COMMAND,
    SKILL_OPERATOR_CATALOG_LIST_COMMAND, SKILL_OPERATOR_CHANGED_COMMAND,
    SKILL_OPERATOR_CONFIG_WRITE_COMMAND, SKILL_OPERATOR_ENABLEMENT_COMMAND,
    SKILL_OPERATOR_MARKDOWN_READ_COMMAND, SKILL_OPERATOR_UNWATCH_COMMAND,
    SKILL_OPERATOR_WATCH_COMMAND, SKILL_SERVICE_ID, SKILL_SERVICE_SNAPSHOT_COMMAND,
    SKILL_SNAPSHOT_COMMAND, SKILL_STATUS_COMMAND, SKILL_TOOL_CATALOG_COMMAND,
    SKILL_TOOL_INVOKE_COMMAND,
};
