[package]
name = "macaca-mcp"
version.workspace = true
edition.workspace = true

[dependencies]
macaca-proto = { workspace = true }
macaca-tools = { workspace = true }
macaca-driver = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
[dev-dependencies]
tokio = { workspace = true }