[package]
name = "macaca-cli"
version.workspace = true
edition.workspace = true

[features]
default = []
systemd = ["sd-notify"]

[dependencies]
macaca-proto = { workspace = true }
macaca-kernel = { workspace = true }
macaca-llm = { workspace = true }
macaca-agent = { workspace = true }
macaca-app = { workspace = true }
macaca-tools = { workspace = true }
macaca-gateway = { workspace = true }
macaca-sdk = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
flate2 = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
uuid = { workspace = true }
macaca-web = { workspace = true }
sd-notify = { version = "0.4", optional = true }

[[bin]]
name = "macaca"
path = "src/main.rs"
