//! Summary context engine — compaction layered on pruning (**Decorator** + **Strategy**).
//!
//! Runtime flow:
//! 1. Delegate to the inner pruning engine to normalize oversized/untrusted sources.
//! 2. Evaluate token pressure against the compaction policy.
//! 3. When compaction triggers, synthesize a reference-only summary message.
//! 4. Preserve the leading system prompt and the most recent interaction tail.
//! 5. Notify lifecycle hooks before and after compaction for external audit sinks.

use std::sync::Arc;

use async_trait::async_trait;
use macaca_proto::{LlmMessage, MacacaResult};
use tracing::info;

use crate::compaction::{
    CompactionHookInput, CompactionLifecycleHook, CompactionPolicy, CompactionSummaryEnvelope,
    CompactionTrigger, NoopCompactionLifecycleHook, SessionLineage, ThresholdCompactionPolicy,
};
use crate::report::{ContextDecisionReport, ContextSourceKind, ContextSourceReport};

use super::helpers::estimate_messages_tokens;
use super::pruning::PruningContextEngine;
use super::types::{ContextAssembleInput, ContextAssembleResult, ContextEngine, ContextEngineInfo};

/// Engine that layers compaction semantics on top of pruning.
#[derive(Clone)]
pub struct SummaryContextEngine {
    pruning: PruningContextEngine,
    compaction_policy: ThresholdCompactionPolicy,
    hooks: Arc<dyn CompactionLifecycleHook>,
}

impl std::fmt::Debug for SummaryContextEngine {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SummaryContextEngine")
            .field("compaction_policy", &self.compaction_policy)
            .finish_non_exhaustive()
    }
}

impl Default for SummaryContextEngine {
    fn default() -> Self {
        Self {
            pruning: PruningContextEngine::default(),
            compaction_policy: ThresholdCompactionPolicy::default(),
            hooks: Arc::new(NoopCompactionLifecycleHook),
        }
    }
}

impl SummaryContextEngine {
    pub const ID: &'static str = "summary";
}

#[async_trait]
impl ContextEngine for SummaryContextEngine {
    fn info(&self) -> ContextEngineInfo {
        ContextEngineInfo::new(Self::ID, "Summary Context Engine")
    }

    async fn assemble(&self, input: ContextAssembleInput) -> MacacaResult<ContextAssembleResult> {
        let estimated_tokens = estimate_messages_tokens(&input.base_messages);
        let decision = self.compaction_policy.decide(&CompactionTrigger {
            estimated_tokens,
            token_budget: input.budget.input_budget(),
            manual: false,
            focus_topic: None,
        });
        let mut result = self.pruning.assemble(input.clone()).await?;
        result.report.engine_id = Self::ID.into();
        let should_summarize = decision.should_compact && result.messages.len() > 3;
        if should_summarize {
            let sid = result
                .report
                .session_id
                .clone()
                .unwrap_or_else(|| "unknown".into());
            let lineage = SessionLineage::root(&sid);
            let hook_in = CompactionHookInput {
                lineage,
                source_segment_id: format!("segment-{sid}"),
                estimated_tokens,
            };
            self.hooks.before_compaction(hook_in.clone()).await?;
            let envelope = CompactionSummaryEnvelope {
                root_session_id: sid.clone(),
                source_segment_id: "current".into(),
                successor_segment_id: "next".into(),
                resolved: vec!["Earlier context was compacted for budget management.".into()],
                decisions: vec![format!(
                    "Generated by SummaryContextEngine ({}).",
                    decision.reason
                )],
                current_state: "Recent messages are preserved below.".into(),
                open_questions: Vec::new(),
                active_task: "Continue from the latest user request.".into(),
                important_ids_and_paths: Vec::new(),
            };
            let summary_body = envelope.render_reference_only();
            let summary = LlmMessage::system(summary_body.clone());
            let recent_start = result.messages.len().saturating_sub(2);
            let mut compacted = Vec::new();
            if let Some(first) = result.messages.first().cloned() {
                compacted.push(first);
            }
            compacted.push(summary);
            compacted.extend(result.messages[recent_start..].iter().cloned());
            result.messages = compacted;
            result.report.decisions.push(ContextDecisionReport::info(
                "context_summary_inserted",
                "Summary engine inserted a reference-only compaction summary.",
            ));
            let tok = envelope.estimated_tokens();
            result.report.sources.push(
                ContextSourceReport::included(
                    "compaction_summary/current",
                    ContextSourceKind::CompactionSummary,
                    "Reference-only compaction summary",
                    tok,
                    summary_body.len(),
                )
                .with_rendering(
                    "summary",
                    "untrusted",
                    Some("compaction/auto".into()),
                    0,
                ),
            );
            let compaction_reason = decision.reason.clone();
            result.report.decisions.push(ContextDecisionReport::info(
                "compaction_hooks",
                compaction_reason.clone(),
            ));
            info!(
                engine_id = Self::ID,
                session_id = %sid,
                estimated_tokens,
                compacted_messages = result.messages.len(),
                reason = %compaction_reason,
                "context engine inserted compaction summary"
            );
            self.hooks.after_compaction(hook_in).await?;
        }
        Ok(result)
    }
}
